quarkus.http.port=9090
quarkus.log.console.json.enabled=false

debezium.engine.name=examples
debezium.engine.database.hostname=postgres
debezium.engine.database.dbname=postgres
debezium.engine.database.port=5432
debezium.engine.database.user=postgres
debezium.engine.database.password=postgres
debezium.engine.publication.name=debezium
debezium.engine.slot.name=debezium
debezium.engine.plugin.name=pgoutput
debezium.engine.snapshot.mode=NO_DATA
debezium.engine.topic.prefix=default
debezium.engine.offset.storage=org.apache.kafka.connect.storage.MemoryOffsetBackingStore

debezium.avro.format=CONFLUENT
debezium.avro.properties.schema.registry.url=http://schema-registry:8080/apis/ccompat/v7

debezium.output.iceberg.threshold.records=10
debezium.output.iceberg.threshold.time=5m
debezium.output.iceberg.name=examples

debezium.output.iceberg.properties.type=hive
debezium.output.iceberg.properties.uri=thrift://hive-metastore:9083
debezium.output.iceberg.properties.io-impl=org.apache.iceberg.aws.s3.S3FileIO
debezium.output.iceberg.properties.warehouse=s3a://warehouse/hive-warehouse
debezium.output.iceberg.properties.s3.endpoint=http://minio:9000
debezium.output.iceberg.properties.s3.access-key-id=admin
debezium.output.iceberg.properties.s3.secret-access-key=password
debezium.output.iceberg.properties.s3.path-style-access=true
debezium.output.iceberg.properties.s3.client-factory-impl=io.debezium.postgres2lake.iceberg.infrastructure.InstrumentedS3FileIOAwsClientFactory

debezium.output.iceberg.file-io.properties.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
debezium.output.iceberg.file-io.properties.fs.s3a.endpoint=http://minio:9000
debezium.output.iceberg.file-io.properties.fs.s3a.path.style.access=true
debezium.output.iceberg.file-io.properties.fs.s3a.access.key=admin
debezium.output.iceberg.file-io.properties.fs.s3a.secret.key=password
