----liquibase formatted sql
----changeset setup:1
--
--CREATE TABLE IF NOT EXISTS data
--(
--    primary_key                            BIGINT PRIMARY KEY,
--    required_column_smallint               SMALLINT                      NOT NULL,
--    required_column_integer                INTEGER                       NOT NULL,
--    required_column_bigint                 BIGINT                        NOT NULL,
--    required_column_decimal                DECIMAL                       NOT NULL,
--    required_column_numeric                NUMERIC(36, 10)               NOT NULL,
--    required_column_real                   REAL                          NOT NULL,
--    required_column_double_precision       DOUBLE PRECISION              NOT NULL,
--    required_column_char                   CHAR(1)                       NOT NULL,
--    required_column_varchar                VARCHAR(255)                  NOT NULL,
--    required_column_text                   TEXT                          NOT NULL,
--    required_column_timestamp              TIMESTAMP WITHOUT TIME ZONE   NOT NULL,
--    required_column_timestamp_tz           TIMESTAMP WITH TIME ZONE      NOT NULL,
--    required_column_date                   DATE                          NOT NULL,
--    required_column_time                   TIME WITHOUT TIME ZONE        NOT NULL,
--    required_column_boolean                BOOLEAN                       NOT NULL,
--    required_column_uuid                   UUID                          NOT NULL,
--
--    optional_column_smallint               SMALLINT,
--    optional_column_integer                INTEGER,
--    optional_column_bigint                 BIGINT,
--    optional_column_decimal                DECIMAL,
--    optional_column_numeric                NUMERIC(36, 10),
--    optional_column_real                   REAL,
--    optional_column_double_precision       DOUBLE PRECISION,
--    optional_column_char                   CHAR(1),
--    optional_column_varchar                VARCHAR(255),
--    optional_column_text                   TEXT,
--    optional_column_timestamp              TIMESTAMP WITHOUT TIME ZONE,
--    optional_column_timestamp_tz           TIMESTAMP WITH TIME ZONE,
--    optional_column_date                   DATE,
--    optional_column_time                   TIME WITHOUT TIME ZONE,
--    optional_column_boolean                BOOLEAN,
--    optional_column_uuid                   UUID,
--
--    required_column_array_smallint         SMALLINT[]                    NOT NULL,
--    required_column_array_integer          INTEGER[]                     NOT NULL,
--    required_column_array_bigint           BIGINT[]                      NOT NULL,
--    required_column_array_decimal          DECIMAL[]                     NOT NULL,
--    required_column_array_numeric          NUMERIC(36, 10)[]             NOT NULL,
--    required_column_array_real             REAL[]                        NOT NULL,
--    required_column_array_double_precision DOUBLE PRECISION[]            NOT NULL,
--    required_column_array_char             CHAR(1)[]                     NOT NULL,
--    required_column_array_varchar          VARCHAR(255)[]                NOT NULL,
--    required_column_array_text             TEXT[]                        NOT NULL,
--    required_column_array_timestamp        TIMESTAMP WITHOUT TIME ZONE[] NOT NULL,
--    required_column_array_timestamp_tz     TIMESTAMP WITH TIME ZONE[]    NOT NULL,
--    required_column_array_date             DATE[]                        NOT NULL,
--    required_column_array_time             TIME WITHOUT TIME ZONE[]      NOT NULL,
--    required_column_array_boolean          BOOLEAN[]                     NOT NULL,
--    required_column_array_uuid             UUID[]                        NOT NULL,
--
--    optional_column_array_smallint         SMALLINT[],
--    optional_column_array_integer          INTEGER[],
--    optional_column_array_bigint           BIGINT[],
--    optional_column_array_decimal          DECIMAL[],
--    optional_column_array_numeric          NUMERIC(36, 10)[],
--    optional_column_array_real             REAL[],
--    optional_column_array_double_precision DOUBLE PRECISION[],
--    optional_column_array_char             CHAR(1)[],
--    optional_column_array_varchar          VARCHAR(255)[],
--    optional_column_array_text             TEXT[],
--    optional_column_array_timestamp        TIMESTAMP WITHOUT TIME ZONE[],
--    optional_column_array_timestamp_tz     TIMESTAMP WITH TIME ZONE[],
--    optional_column_array_date             DATE[],
--    optional_column_array_time             TIME WITHOUT TIME ZONE[],
--    optional_column_array_boolean          BOOLEAN[],
--    optional_column_array_uuid             UUID[]
--);
--
--CREATE TABLE heartbeat
--(
--    single_row  bool PRIMARY KEY DEFAULT TRUE,
--    "timestamp" TIMESTAMP NOT NULL,
--    CONSTRAINT single_row_check CHECK (single_row)
--);
--
--CREATE TABLE signals
--(
--    id   TEXT NOT NULL PRIMARY KEY,
--    type TEXT NOT NULL,
--    data TEXT
--);
