debezium.engine.name=development
debezium.engine.database.hostname=localhost
debezium.engine.database.dbname=postgres
debezium.engine.database.port=5432
debezium.engine.database.user=postgres
debezium.engine.database.password=postgres
debezium.engine.publication.name=debezium
debezium.engine.slot.name=debezium
debezium.engine.plugin.name=pgoutput
debezium.engine.snapshot.mode=NO_DATA
debezium.engine.topic.prefix=default
debezium.engine.offset.storage=org.apache.kafka.connect.storage.MemoryOffsetBackingStore

debezium.avro=BINARY

output.format=AVRO

output.avro.s3.access-key=admin
output.avro.s3.secret-access-key=password
output.avro.s3.endpoint=http://localhost:9000

output.avro.naming-strategy.partitioner=UNPARTITIONED
output.avro.naming-strategy.file-name=PROCESSING_TIME