debezium.engine.name=development
debezium.engine.database.hostname=localhost
debezium.engine.database.dbname=postgres
debezium.engine.database.port=5432
debezium.engine.database.user=postgres
debezium.engine.database.password=postgres
debezium.engine.publication.name=debezium
debezium.engine.slot.name=debezium
debezium.engine.plugin.name=pgoutput
debezium.engine.snapshot.mode=NO_DATA
debezium.engine.topic.prefix=default
debezium.engine.offset.storage=org.apache.kafka.connect.storage.MemoryOffsetBackingStore

debezium.avro=BINARY

output.format=ICEBERG
output.threshold.records=10
output.threshold.time=5m

output.avro.naming-strategy.partitioner=UNPARTITIONED
output.avro.naming-strategy.file-name=PROCESSING_TIME
output.avro.file-io.properties.fs.s3a.access.key=admin
output.avro.file-io.properties.fs.s3a.secret.key=password
output.avro.file-io.properties.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
output.avro.file-io.properties.fs.s3a.path.style.access=true
output.avro.file-io.properties.fs.s3a.endpoint=http://localhost:9000

output.orc.naming-strategy.partitioner=UNPARTITIONED
output.orc.naming-strategy.file-name=PROCESSING_TIME
output.orc.file-io.properties.fs.s3a.access.key=admin
output.orc.file-io.properties.fs.s3a.secret.key=password
output.orc.file-io.properties.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
output.orc.file-io.properties.fs.s3a.path.style.access=true
output.orc.file-io.properties.fs.s3a.endpoint=http://localhost:9000

output.parquet.naming-strategy.partitioner=UNPARTITIONED
output.parquet.naming-strategy.file-name=PROCESSING_TIME
output.parquet.file-io.properties.fs.s3a.access.key=admin
output.parquet.file-io.properties.fs.s3a.secret.key=password
output.parquet.file-io.properties.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
output.parquet.file-io.properties.fs.s3a.path.style.access=true
output.parquet.file-io.properties.fs.s3a.endpoint=http://localhost:9000

output.iceberg.name=development
output.iceberg.properties.type=jdbc
output.iceberg.properties.uri=jdbc:postgresql://localhost:5432/postgres
output.iceberg.properties.jdbc.user=postgres
output.iceberg.properties.jdbc.password=postgres
output.iceberg.properties.jdbc.schema-version=V1
output.iceberg.properties.io-impl=org.apache.iceberg.aws.s3.S3FileIO
output.iceberg.properties.warehouse=s3a://warehouse
output.iceberg.properties.s3.endpoint=http://localhost:9000
output.iceberg.properties.s3.access-key-id=admin
output.iceberg.properties.s3.secret-access-key=password
output.iceberg.properties.s3.path-style-access=true
output.iceberg.properties.s3.client-factory-impl=io.debezium.postgres2lake.infrastructure.format.iceberg.InstrumentedS3FileIOAwsClientFactory

output.paimon.properties.type=jdbc
output.paimon.properties.warehouse=s3a://warehouse/paimon-warehouse
output.paimon.properties.jdbc-url=jdbc:postgresql://localhost:5432/postgres
output.paimon.properties.jdbc-user=postgres
output.paimon.properties.jdbc-password=postgres
output.paimon.properties.jdbc-driver=org.postgresql.Driver
output.paimon.properties.jdbc-table-prefix=paimon_
output.paimon.file-io.properties.fs.s3a.access.key=admin
output.paimon.file-io.properties.fs.s3a.secret.key=password
output.paimon.file-io.properties.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
output.paimon.file-io.properties.fs.s3a.path.style.access=true
output.paimon.file-io.properties.fs.s3a.endpoint=http://localhost:9000
