debezium.engine.name=development
debezium.engine.database.hostname=localhost
debezium.engine.database.dbname=postgres
debezium.engine.database.port=5432
debezium.engine.database.user=postgres
debezium.engine.database.password=postgres
debezium.engine.publication.name=debezium
debezium.engine.slot.name=debezium
debezium.engine.plugin.name=pgoutput
debezium.engine.snapshot.mode=NO_DATA
debezium.engine.topic.prefix=default
debezium.engine.offset.storage=org.apache.kafka.connect.storage.MemoryOffsetBackingStore

debezium.avro.format=CONFLUENT

debezium.avro.properties.schema.registry.url=http://localhost:8080/apis/ccompat/v7

output.format=PAIMON
output.threshold.records=10
output.threshold.time=5m

output.paimon.properties.type=jdbc
output.paimon.properties.warehouse=s3a://warehouse/paimon-warehouse
output.paimon.properties.jdbc-url=jdbc:postgresql://localhost:5432/postgres
output.paimon.properties.jdbc-user=postgres
output.paimon.properties.jdbc-password=postgres
output.paimon.properties.jdbc-driver=org.postgresql.Driver
output.paimon.properties.jdbc-table-prefix=paimon_
output.paimon.file-io.properties.fs.s3a.access.key=admin
output.paimon.file-io.properties.fs.s3a.secret.key=password
output.paimon.file-io.properties.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
output.paimon.file-io.properties.fs.s3a.path.style.access=true
output.paimon.file-io.properties.fs.s3a.endpoint=http://localhost:9000
