quarkus.log.console.json.enabled=false

debezium.engine.name=development
debezium.engine.database.hostname=localhost
debezium.engine.database.dbname=postgres
debezium.engine.database.port=5432
debezium.engine.database.user=postgres
debezium.engine.database.password=postgres
debezium.engine.publication.name=debezium
debezium.engine.slot.name=debezium
debezium.engine.plugin.name=pgoutput
debezium.engine.snapshot.mode=NO_DATA
debezium.engine.topic.prefix=default
debezium.engine.offset.storage=org.apache.kafka.connect.storage.MemoryOffsetBackingStore

debezium.avro.format=CONFLUENT
debezium.avro.properties.schema.registry.url=http://localhost:8080/apis/ccompat/v7

debezium.output.paimon.threshold.records=10
debezium.output.paimon.threshold.time=5m

debezium.output.paimon.properties.type=jdbc
debezium.output.paimon.properties.warehouse=s3a://warehouse/paimon-warehouse
debezium.output.paimon.properties.jdbc-url=jdbc:postgresql://localhost:5432/postgres
debezium.output.paimon.properties.jdbc-user=postgres
debezium.output.paimon.properties.jdbc-password=postgres
debezium.output.paimon.properties.jdbc-driver=org.postgresql.Driver
debezium.output.paimon.properties.jdbc-table-prefix=paimon_
debezium.output.paimon.file-io.properties.fs.s3a.access.key=admin
debezium.output.paimon.file-io.properties.fs.s3a.secret.key=password
debezium.output.paimon.file-io.properties.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
debezium.output.paimon.file-io.properties.fs.s3a.path.style.access=true
debezium.output.paimon.file-io.properties.fs.s3a.endpoint=http://localhost:9000
