quarkus.log.console.json.enabled=false

debezium.engine.name=development
debezium.engine.database.hostname=localhost
debezium.engine.database.dbname=postgres
debezium.engine.database.port=5432
debezium.engine.database.user=postgres
debezium.engine.database.password=postgres
debezium.engine.publication.name=debezium
debezium.engine.slot.name=debezium
debezium.engine.plugin.name=pgoutput
debezium.engine.snapshot.mode=NO_DATA
debezium.engine.topic.prefix=default
debezium.engine.offset.storage=org.apache.kafka.connect.storage.MemoryOffsetBackingStore

debezium.avro.format=CONFLUENT
debezium.avro.properties.schema.registry.url=http://localhost:8080/apis/ccompat/v7

debezium.output.iceberg.threshold.records=10
debezium.output.iceberg.threshold.time=5m

debezium.output.iceberg.name=development
debezium.output.iceberg.properties.type=jdbc
debezium.output.iceberg.properties.uri=jdbc:postgresql://localhost:5432/postgres
debezium.output.iceberg.properties.jdbc.user=postgres
debezium.output.iceberg.properties.jdbc.password=postgres
debezium.output.iceberg.properties.jdbc.schema-version=V1
debezium.output.iceberg.properties.io-impl=org.apache.iceberg.aws.s3.S3FileIO
debezium.output.iceberg.properties.warehouse=s3a://warehouse
debezium.output.iceberg.properties.s3.endpoint=http://localhost:9000
debezium.output.iceberg.properties.s3.access-key-id=admin
debezium.output.iceberg.properties.s3.secret-access-key=password
debezium.output.iceberg.properties.s3.path-style-access=true
debezium.output.iceberg.properties.s3.client-factory-impl=io.debezium.postgres2lake.iceberg.infrastructure.InstrumentedS3FileIOAwsClientFactory
