quarkus.log.console.json.enabled=false

debezium.engine.name=development
debezium.engine.database.hostname=localhost
debezium.engine.database.dbname=postgres
debezium.engine.database.port=5432
debezium.engine.database.user=postgres
debezium.engine.database.password=postgres
debezium.engine.publication.name=debezium
debezium.engine.slot.name=debezium
debezium.engine.plugin.name=pgoutput
debezium.engine.snapshot.mode=NO_DATA
debezium.engine.topic.prefix=default
debezium.engine.offset.storage=org.apache.kafka.connect.storage.MemoryOffsetBackingStore

debezium.avro.format=CONFLUENT
debezium.avro.properties.schema.registry.url=http://localhost:8080/apis/ccompat/v7

debezium.output.parquet.threshold.records=10
debezium.output.parquet.threshold.time=5m

debezium.output.parquet.naming-strategy.partitioner=UNPARTITIONED
debezium.output.parquet.naming-strategy.file-name=PROCESSING_TIME
debezium.output.parquet.naming-strategy.storage=S3
debezium.output.parquet.naming-strategy.target-path=warehouse
debezium.output.parquet.file-io.properties.fs.s3a.access.key=admin
debezium.output.parquet.file-io.properties.fs.s3a.secret.key=password
debezium.output.parquet.file-io.properties.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
debezium.output.parquet.file-io.properties.fs.s3a.path.style.access=true
debezium.output.parquet.file-io.properties.fs.s3a.endpoint=http://localhost:9000
