name: debezium-examples-avro

include:
  - path: ../common/base-compose.yaml

services:
  app:
    image: local/debezium-postgres2lake-avro:${IMAGE_TAG:-0.1.0}
    depends_on:
      postgres:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
      schema-registry:
        condition: service_started
      mc:
        condition: service_started
    ports:
      - "9090:9090"
    volumes:
      - ./config/application.properties:/work/config/application.properties:ro
