quarkus.http.port=9090

quarkus.log.category."org.apache.kafka.common.config.AbstractConfig".level=ERROR
quarkus.log.category."io.micrometer.core.instrument.MeterRegistry".level=ERROR

# https://github.com/quarkusio/quarkus/issues/31420
platform.quarkus.native.builder-image=false
