quarkus.http.port=9090

debezium.engine.name=examples
debezium.engine.database.hostname=postgres
debezium.engine.database.dbname=postgres
debezium.engine.database.port=5432
debezium.engine.database.user=postgres
debezium.engine.database.password=postgres
debezium.engine.publication.name=debezium
debezium.engine.slot.name=debezium
debezium.engine.plugin.name=pgoutput
debezium.engine.snapshot.mode=NO_DATA
debezium.engine.topic.prefix=default
debezium.engine.offset.storage=org.apache.kafka.connect.storage.MemoryOffsetBackingStore

debezium.avro.format=CONFLUENT
debezium.avro.properties.schema.registry.url=http://schema-registry:8080/apis/ccompat/v7

debezium.output.orc.threshold.records=10
debezium.output.orc.threshold.time=5m
debezium.output.orc.naming-strategy.partitioner=UNPARTITIONED
debezium.output.orc.naming-strategy.file-name=PROCESSING_TIME
debezium.output.orc.naming-strategy.storage=S3
debezium.output.orc.naming-strategy.target-path=warehouse
# HDFS example:
# debezium.output.orc.naming-strategy.storage=HDFS
# debezium.output.orc.naming-strategy.target-path=/warehouse

debezium.output.orc.file-io.properties.fs.s3a.access.key=admin
debezium.output.orc.file-io.properties.fs.s3a.secret.key=password
debezium.output.orc.file-io.properties.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
debezium.output.orc.file-io.properties.fs.s3a.path.style.access=true
debezium.output.orc.file-io.properties.fs.s3a.endpoint=http://minio:9000
