debezium.engine.name=development
debezium.engine.database.hostname=localhost
debezium.engine.database.dbname=postgres
debezium.engine.database.port=5432
debezium.engine.database.user=postgres
debezium.engine.database.password=postgres
debezium.engine.publication.name=debezium
debezium.engine.slot.name=debezium
debezium.engine.plugin.name=pgoutput
debezium.engine.snapshot.mode=NO_DATA
debezium.engine.topic.prefix=default
debezium.engine.offset.storage=org.apache.kafka.connect.storage.MemoryOffsetBackingStore

debezium.avro.format=CONFLUENT

debezium.avro.properties.schema.registry.url=http://localhost:8080/apis/ccompat/v7

output.format=AVRO
output.threshold.records=10
output.threshold.time=5m

output.avro.naming-strategy.partitioner=UNPARTITIONED
output.avro.naming-strategy.file-name=PROCESSING_TIME
output.avro.file-io.properties.fs.s3a.access.key=admin
output.avro.file-io.properties.fs.s3a.secret.key=password
output.avro.file-io.properties.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
output.avro.file-io.properties.fs.s3a.path.style.access=true
output.avro.file-io.properties.fs.s3a.endpoint=http://localhost:9000
